import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Head from 'next/head';

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["100", "300", "400", "500", "600"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600&display=swap" />
      </Head>
      <body
        className={cn(
          "relative h-full antialiased font-sans",
          poppins.className
        )}
      >
        <main className="relative flex flex-col min-h-screen">{children}</main>
      </body>
    </html>
  );
}
