export const HOME_PATH = '/'
export const COURSEADDER_HOME = '/courseForm'
export const COURSE_PATH = '/courses';
export const BRANCH_PATH = '/branches';
export const TUTION_PATH = '/tutions';
export const CONTACT_US_PATH = '/contactUs'
export const PLACEMENT_PATH = '/placements';
export const HIREFROMUS_PATH = '/hireFromUs';
export const OFFLINE_BRANCHES = '/offlineBranches';
export const OFFLINE_CENTRES = 'offlineCentres'
export const UPCOMING_BATCHES = '/courses/upcomingBatches'
export const COMBINED_BRANCHES = '/combinedBranches'
export const COUNSELLOR_SECTION = '/internalplacementstatistics';
export const INTERNAL_STATS='/internalStats';
export const NAV_BAR='/navbar';
export const COURSE_NAV_BAR='/coursenav';
export const BRANCH_NAV_BAR='/branchnav';
export const SIGN_IN = '/signin'
export const SIGN_UP = '/signUp'
export const PROD_URL = 'http://37.61.213.213:8090/';
export const PROD2_URL = 'http://106.51.76.167:8080/';
