export const HOME_PATH = '/'
export const COURSE_PATH = '/courses';
export const BRANCH_PATH = '/branches';
export const TUTION_PATH = '/tutions';
export const CONTACT_US_PATH = '/contactUs'
export const PLACEMENT_PATH='/placements';
export const OFFLINE_BRANCHES='/offlineBranches';
export const OFFLINE_CENTRES='/offlineBranches/offlineCentres'
export const UPCOMING_BATCHES='/courses/upcomingBatches'
export const COMBINED_BRANCHES='/combinedBranches'